

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'


- script: |
    npm install -g npm@latest
    npm install -g @angular/cli
  displayName: 'Install npm and Angular CLI'


- script: cd portplace
  displayName: 'Navigate to project folder'


- script: |
    npm install 
    npm run build
  displayName: 'npm install and build'
 
